### ISSUE TITLE
Unable to figure out error (ValueError)

### ISSUE THREAD

**Issue by mohitsrinivasan** [stephane-caron/qpsolvers#16]
Hi,

I am getting an error called "ValueError: Buffer has wrong number of dimensions (expected 1, got 2). I don't think there is anything wrong in the way I am declaring my QP. Do you think I am missing something really minor?

Thanks a lot!

Best,
Mohit

**Comment by stephane-caron** [comment]
That's a generic Cython error from buffer/memory view. It's likely that you are not building one of your problem matrices correctly.

Can you provide a minimal example that reproduces this error?
