### ISSUE TITLE
relative path issue?

### ISSUE THREAD

**Issue by microprediction** [stephane-caron/qpsolvers#163]
I noticed the use of relative paths everywhere and wonder if this is related: 

        Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ] on darwin
        Type "help", "copyright", "credits" or "license" for more information.
        >>> import qpsolvers
        >>> from qpsolvers import Problem
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
        ImportError: cannot import name 'Problem' from 'qpsolvers' (/opt/homebrew/Caskroom/miniforge/base/envs/qpsolvers/lib/python3.10/site-packages/qpsolvers/__init__.py)

**Comment by stephane-caron** [comment]
Relative paths should be fine :thinking: I tried to reproduce your issue as follows but the import works:

```console
$ conda create -n qpsolvers-test python=3.10.8
$ conda activate qpsolvers-test
$ conda install qpsolvers
$ python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import qpsolvers
>>> from qpsolvers import Problem
>>> print(Problem)
<class 'qpsolvers.problem.Problem'>
```

Is your version of `qpsolvers` up to date? Can you `print(qpsolvers.__version__)`?

**Comment by microprediction** [comment]
Hmmm this is probably just another episode in the neverending hassles of mac M2. I should probably just switch back to a different machine but if I get it working I'll make a PR. 

                
                (base) peter@Peters-MacBook-Air ~ % conda create -n qpsolvers-test python=3.10.8
                Collecting package metadata (current_repodata.json): done
                Solving environment: done
                
                ## Package Plan ##
                
                  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/qpsolvers-test
                
                  added / updated specs:
                    - python=3.10.8
                
                
                The following NEW packages will be INSTALLED:
                
                  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4
                  ca-certificates    conda-forge/osx-arm64::ca-certificates-2022.12.7-h4653dfc_0
                  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
                  libsqlite          conda-forge/osx-arm64::libsqlite-3.40.0-h76d750c_0
                  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h03a7124_4
                  ncurses            conda-forge/osx-arm64::ncurses-6.3-h07bb92c_1
                  openssl            conda-forge/osx-arm64::openssl-3.0.7-h03a7124_2
                  pip                conda-forge/noarch::pip-22.3.1-pyhd8ed1ab_0
                  python             conda-forge/osx-arm64::python-3.10.8-h3ba56d0_0_cpython
                  readline           conda-forge/osx-arm64::readline-8.1.2-h46ed386_0
                  setuptools         conda-forge/noarch::setuptools-66.1.1-pyhd8ed1ab_0
                  tk                 conda-forge/osx-arm64::tk-8.6.12-he1e0b03_0
                  tzdata             conda-forge/noarch::tzdata-2022g-h191b570_0
                  wheel              conda-forge/noarch::wheel-0.38.4-pyhd8ed1ab_0
                  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0
                
                
                Proceed ([y]/n)? y
                
                
                Downloading and Extracting Packages
                
                Preparing transaction: done
                Verifying transaction: done
                Executing transaction: done
                #
                # To activate this environment, use
                #
                #     $ conda activate qpsolvers-test
                #
                # To deactivate an active environment, use
                #
                #     $ conda deactivate
                
                (base) peter@Peters-MacBook-Air ~ % conda activate qpsolvers-test
                (qpsolvers-test) peter@Peters-MacBook-Air ~ % conda install qpsolvers
                Collecting package metadata (current_repodata.json): done
                Solving environment: failed with initial frozen solve. Retrying with flexible solve.
                Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
                Collecting package metadata (repodata.json): done
                Solving environment: done
                
                ## Package Plan ##
                
                  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/qpsolvers-test
                
                  added / updated specs:
                    - qpsolvers
                
                
                The following NEW packages will be INSTALLED:
                
                  appdirs            conda-forge/noarch::appdirs-1.4.4-pyh9f0ad1d_0
                  brotlipy           conda-forge/osx-arm64::brotlipy-0.7.0-py310h8e9501a_1005
                  certifi            conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0
                  cffi               conda-forge/osx-arm64::cffi-1.15.1-py310h2399d43_3
                  charset-normalizer conda-forge/noarch::charset-normalizer-2.1.1-pyhd8ed1ab_0
                  cryptography       conda-forge/osx-arm64::cryptography-39.0.0-py310hfc83b78_0
                  cvxopt             conda-forge/osx-arm64::cvxopt-1.3.0-py310h3e41943_4
                  cython             conda-forge/osx-arm64::cython-0.29.33-py310h0f1eb42_0
                  dsdp               conda-forge/osx-arm64::dsdp-5.8-h9397a75_1203
                  ecos               conda-forge/osx-arm64::ecos-2.0.11-py310hf1a086a_0
                  fftw               conda-forge/osx-arm64::fftw-3.3.10-nompi_h3046061_106
                  glpk               conda-forge/osx-arm64::glpk-5.0-h6d7a090_0
                  gmp                conda-forge/osx-arm64::gmp-6.2.1-h9f76cd9_0
                  gsl                conda-forge/osx-arm64::gsl-2.7-h6e638da_0
                  idna               conda-forge/noarch::idna-3.4-pyhd8ed1ab_0
                  libblas            conda-forge/osx-arm64::libblas-3.9.0-16_osxarm64_openblas
                  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-16_osxarm64_openblas
                  libcxx             conda-forge/osx-arm64::libcxx-14.0.6-h2692d47_0
                  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-11_3_0_hd922786_27
                  libgfortran5       conda-forge/osx-arm64::libgfortran5-11.3.0-hdaf2cc0_27
                  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-16_osxarm64_openblas
                  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.21-openmp_hc731615_3
                  libqdldl           conda-forge/osx-arm64::libqdldl-0.1.5-hb7217d7_1
                  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-15.0.7-h7cfbb63_0
                  metis              conda-forge/osx-arm64::metis-5.1.0-h9f76cd9_1006
                  mpfr               conda-forge/osx-arm64::mpfr-4.1.0-h6d7a090_1
                  numpy              conda-forge/osx-arm64::numpy-1.24.1-py310h3d2048e_0
                  osqp               conda-forge/osx-arm64::osqp-0.6.2.post0-py310hdead3df_3
                  packaging          conda-forge/noarch::packaging-23.0-pyhd8ed1ab_0
                  pooch              conda-forge/noarch::pooch-1.6.0-pyhd8ed1ab_0
                  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
                  pyopenssl          conda-forge/noarch::pyopenssl-23.0.0-pyhd8ed1ab_0
                  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6
                  python_abi         conda-forge/osx-arm64::python_abi-3.10-3_cp310
                  qdldl-python       conda-forge/osx-arm64::qdldl-python-0.1.5.post2-py310h2b830bf_0
                  qpsolvers          conda-forge/noarch::qpsolvers-2.6.0-pyhd8ed1ab_0
                  quadprog           conda-forge/osx-arm64::quadprog-0.1.11-py310hea002bf_1
                  requests           conda-forge/noarch::requests-2.28.2-pyhd8ed1ab_0
                  scipy              conda-forge/osx-arm64::scipy-1.10.0-py310ha0d8a01_0
                  suitesparse        conda-forge/osx-arm64::suitesparse-5.10.1-h7cd81ec_1
                  tbb                conda-forge/osx-arm64::tbb-2021.7.0-hffc8910_1
                  urllib3            conda-forge/noarch::urllib3-1.26.14-pyhd8ed1ab_0
                
                
                Proceed ([y]/n)? y
                
                
                Downloading and Extracting Packages
                
                Preparing transaction: done
                Verifying transaction: done
                Executing transaction: done
                (qpsolvers-test) peter@Peters-MacBook-Air ~ % import qpsolvers
                zsh: command not found: import
                (qpsolvers-test) peter@Peters-MacBook-Air ~ % from qpsolvers import Problem
                from: can't read /var/mail/qpsolvers
                (qpsolvers-test) peter@Peters-MacBook-Air ~ % python
                Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ] on darwin
                Type "help", "copyright", "credits" or "license" for more information.
                >>> import qpsolvers
                >>> from qpsolvers import Problem
                Traceback (most recent call last):
                  File "<stdin>", line 1, in <module>
                ImportError: cannot import name 'Problem' from 'qpsolvers' (/opt/homebrew/Caskroom/miniforge/base/envs/qpsolvers-test/lib/python3.10/site-packages/qpsolvers/__init__.py)

**Comment by microprediction** [comment]
Okay got it ... you were right of course I hadn't done the pip --upgrade as well as the conda one, so I was still on 2.6.0

**Comment by stephane-caron** [comment]
Cool, I'm glad it worked out :smiley:
