### ISSUE TITLE
OSQP import name collision

### ISSUE THREAD

**Issue by nikolaif399** [stephane-caron/qpsolvers#17]
I'm seeing a name collision when using the osqp solver with this package. Specifically, accessing osqp.constant fails because osqp refers to both the module name and the initialized osqp solver object.

In osqp_.py:
`from osqp import OSQP`
and
`osqp = OSQP()`

leads to the above conflict. I'm working on a pull request now that removes the collision.

**Comment by nikolaif399** [comment]
Update: I didn't realize non-master push access was restricted on this repo.

I have a local branch that works for me, I'm happy to push it up if this is a problem for more users than me. 

To reproduce the error I'm seeing, just run test_solvers.py with osqp in the available solvers list. The error I'm seeing is 

> Traceback (most recent call last):
  File "test_solvers.py", line 69, in <module>
    expected_sol = solve_qp(solver=available_solvers[0], **case)
  File "/home/nflowers/anaconda3/envs/rml/lib/python3.7/site-packages/qpsolvers/__init__.py", line 183, in solve_qp
    return osqp_solve_qp(P, q, G, h, A, b, initvals=initvals)
  File "/home/nflowers/anaconda3/envs/rml/lib/python3.7/site-packages/qpsolvers/osqp_.py", line 101, in osqp_solve_qp
    if res.info.status_val != osqp.constant('OSQP_SOLVED'):
NameError: name 'osqp' is not defined

**Comment by stephane-caron** [comment]
> accessing osqp.constant fails because osqp refers to both the module name and the initialized osqp solver object.

Hmm, but then why would it fail at this precise call, and not from one of the earlier calls to e.g. ``osqp.solve()`` or ``osqp.setup()``? :thinking: 

At any rate, naming the variable after the module name was bad, I just pushed a renaming for it. Thanks for reporting this!

@nikolaif399 Since I don't get the same error as you on my system, could you check that the error has disappeared for you with the latest ``master``?

**Comment by nikolaif399** [comment]
Hmm that is strange, I'm not sure why it failed at that particular point. Either way, your latest commit fixed the issue, thanks for pushing that up!
