### ISSUE TITLE
How can I set verbosity?

### ISSUE THREAD

**Issue by dmeoli** [stephane-caron/qpsolvers#19]
Is there a way to set the verbosity mode in a more generic way?

If I use `solve_qp(..., solver=cvxopt)` I can do that as:

`qp_solvers.cvxopt_.options['show_progress'] = True`

and for the other solvers? I wish I could manage verbosity independently of the type of solver.

Tip: wouldn't it be better to add a verbose parameter to the `solve_qp` method?

**Comment by stephane-caron** [comment]
This would be a nice feature indeed!

I've just added a `verbose` parameter to `solve_qp` as you suggest. It only applies to CVXOPT, MOSEK and qpOASES for now.

I will gladly merge PRs adding support for this argument to more solvers :wink:

**Comment by dmeoli** [comment]
Thx @stephane-caron, I needed such an interface like this for my SVMs project I'm working on.
Could you make this version available on PyPI repo asap?

Anyway, I don't think that this option is available for all solvers, for example in `quadprog` there doesn't seem to be a verbose option :(

**Comment by stephane-caron** [comment]
Sure, just pushed it to PyPI with `v1.2.1`.

> Anyway, I don't think that this option is available for all solvers, for example in quadprog there doesn't seem to be a verbose option :(

The new version extends the ``verbose`` keyword to all solvers, except quadprog which is the only solver that does not provide a verbosity option. You can ask for this feature in the [quadprog issue tracker](https://github.com/rmcgibbo/quadprog/issues): if it becomes available, I will integrate it here :wink:

**Comment by dmeoli** [comment]
Thx @stephane-caron, you are the best! 
I just opened an [issue](https://github.com/rmcgibbo/quadprog/issues/new), I'll let you know!

**Comment by stephane-caron** [comment]
Closing this issue for now, feel free to re-open if there's an update.
