### ISSUE TITLE
ValueError and TypeError when using solve_qp

### ISSUE THREAD

**Issue by shyney7** [stephane-caron/qpsolvers#23]
Hi I want do use a Support Vector Machine for a Linear Separable Dataset.
I've already managed to solve it with matlab and the quadprog() function.

Now what I've done is just translate the exact same code to python to be able to solve it on my google colab notebook. 
Unfortunately Im getting two errors:
 
```
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/qpsolvers/quadprog_.py in quadprog_solve_qp(P, q, G, h, A, b, initvals, verbose)
     87     try:
---> 88         return solve_qp(qp_G, qp_a, qp_C, qp_b, meq)[0]
     89     except ValueError as e:

quadprog/quadprog.pyx in quadprog.solve_qp()

ValueError: matrix G is not positive definite

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
2 frames
<ipython-input-57-fef196ccfda0> in <module>()
     23 print('b\n')
     24 print(b)
---> 25 v = solve_qp(H,f,A,b)

/usr/local/lib/python3.6/dist-packages/qpsolvers/__init__.py in solve_qp(P, q, G, h, A, b, lb, ub, solver, initvals, sym_proj, verbose, **kwargs)
    260         return qpoases_solve_qp(*args, **kwargs)
    261     elif solver == 'quadprog':
--> 262         return quadprog_solve_qp(*args, **kwargs)
    263     raise Exception("solver '%s' not recognized" % solver)
    264 

/usr/local/lib/python3.6/dist-packages/qpsolvers/quadprog_.py in quadprog_solve_qp(P, q, G, h, A, b, initvals, verbose)
     88         return solve_qp(qp_G, qp_a, qp_C, qp_b, meq)[0]
     89     except ValueError as e:
---> 90         if "matrix G is not positive definite" in e:
     91             # quadprog writes G the cost matrix that we write P in this package
     92             raise ValueError("matrix P is not positive definite")

TypeError: argument of type 'ValueError' is not iterable
```
Here is the colab link:
https://colab.research.google.com/drive/10ILReXmCO0JNBKS5SuEZouXB55VyiDnE?usp=sharing

I've added also the working matlab code at the bottom of the notebook so that you can see that its just a one by one translation of the code. I cant figure out why its not working with python since it works perfectly on matlab.

If you look at the matlab documentation for quadprog() it seems its used the same way as the solve_qp() function here:
https://de.mathworks.com/help/optim/ug/quadprog.html

I hope you can help me. I know that this issue might not be a bug but rather a user error

**Comment by shyney7** [comment]
Ok I managed to solve it by myself by specifying the solver like this:
`v = solve_qp(H,f,A,b, solver=sparse_solvers[0])`
This gave me the right result that I was expecting.
Is there a way to print out all available solvers?

**Comment by stephane-caron** [comment]
The way you build your cost function matrix `H`:
```python
H = np.zeros((m+1, m+1))
for i in range(np.size(H,0)-1):
  H[i,i] = 1.0
```
It cannot be [positive semidefinite](https://en.wikipedia.org/wiki/Definite_symmetric_matrix) because `H[m, m] == 0`. Many QP solvers, including [quadprog](https://github.com/rmcgibbo/quadprog) which is the default, will only work with positive semidefinite matrices. But indeed you can try with other solvers.

>  Is there a way to print out all available solvers?

Sure:
```python
import qpsolvers
print(qpsolvers.available_solvers)
```
