### ISSUE TITLE
quadprog is looking for new maintainers

### ISSUE THREAD

**Issue by rmcgibbo** [stephane-caron/qpsolvers#24]
Hi all! I just wanted to ping re: https://github.com/rmcgibbo/quadprog/issues/13 that I'm looking for new maintainers to take over `quadprog`. Perhaps some of the people involved in this repository would be interested in that role, so I wanted to give you a heads up.

**Comment by stephane-caron** [comment]
Looks like `quadprog` found two new caring maintainers, fantastic! :grinning: :+1: :tada:
