### ISSUE TITLE
Building wheel for quadprog (setup.py) ... error

### ISSUE THREAD

**Issue by Viator99** [stephane-caron/qpsolvers#28]
i'm becoming mad, pls help me
![Screenshot (169)](https://user-images.githubusercontent.com/45045229/99253447-11049480-2811-11eb-9410-fc99deb547f7.png)

**Comment by tytcc** [comment]
It seems that you need  install Mircrosoft Visual C++ 14.0 or greater. May be this can be helpful to you:
https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29

**Comment by Viator99** [comment]
> 
> 
> It seems that you need install Mircrosoft Visual C++ 14.0 or greater. May be this can be helpful to you:
> https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29

thank you so much, it is installed now
