### ISSUE TITLE
Feature request: qpmad solver

### ISSUE THREAD

**Issue by david-cortes** [stephane-caron/qpsolvers#29]
The solver [qpmad](https://github.com/asherikov/qpmad) looks promising for inclusion. It implements the Goldfarb-Idnani method, and seems to work faster than others (e.g. qpOASES) with dense inputs. There's an R wrapper for it too: https://github.com/anderic1/qpmadr

**Comment by stephane-caron** [comment]
Interesting solver! Thanks for sharing this.

It looks like it doesn't have Python bindings for now, but I'll gladly merge a PR for it when it does :slightly_smiling_face:

**Comment by stephane-caron** [comment]
Closing this issue for now as qpmad doesn't provide Python bindings. You can request this feature in [qpmad's issue tracker](https://github.com/asherikov/qpmad/issues). Feel free to re-open here if Python bindings become available.
