### ISSUE TITLE
Updating the Gurobi interface

### ISSUE THREAD

**Issue by DKenefake** [stephane-caron/qpsolvers#34]
With Gurobi's 9.0 update, they have included a matrix API that is much faster. It lets you add the entire constraint set in one go. I have an example implementation that I could contribute [here](https://github.com/DKenefake/SimpleDenseGurobi/blob/main/simple_gurobi.py). In my experience, this drops the overhead to the solver drastically.

**Comment by stephane-caron** [comment]
This sounds great, I'll gladly merge a PR for it :grinning: Can you adapt `gurobi_solve_qp` in `gurobi_.py` to use this new API?

**Comment by DKenefake** [comment]
I have just submitted a PR for it. 

#38

**Comment by stephane-caron** [comment]
Thanks a lot for this contribution! As discussed in the PR, the performance improvement is significant, e.g. on the `sparse_problem.py` example with `n=200`:

- before: `4.55 ms ± 38.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`
- after: `36.3 ms ± 89.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)`
