### ISSUE TITLE
Error: Microsoft Visual C++ 14.0 is required (compile in ChimeraX)

### ISSUE THREAD

**Issue by Yongcheng123** [stephane-caron/qpsolvers#41]
> Traceback (most recent call last):
> File "C:\Program Files\ChimeraX 1.1\bin\lib\site-packages\chimerax\toolshed_utils\__init__.py", line 489, in _pip_install
> results = _run_pip(command, logger)
> 
> File "C:\Program Files\ChimeraX 1.1\bin\lib\site-packages\chimerax\toolshed_utils\__init__.py", line 540, in _run_pip
> raise RuntimeError(s)
> RuntimeError: Looking in indexes: https://pypi.org/simple, https://cxtoolshed.rbvi.ucsf.edu/pypi/ 
> Processing z:\plugin_dl\dist\chimerax_dlstruct-0.1-py3-none-any.whl 
> Requirement already satisfied: ChimeraX-Core~=1.0 in c:\program files\chimerax 1.1\bin\lib\site-packages (from ChimeraX-DLStruct==0.1) (1.1) 
> Requirement already satisfied: numpy~=1.16.4 in c:\users\ymu\appdata\local\ucsf\chimerax\1.1\site-packages (from ChimeraX-DLStruct==0.1) (1.16.6) 
> Requirement already satisfied: torch~=1.7.1 in c:\users\ymu\appdata\local\ucsf\chimerax\1.1\site-packages (from ChimeraX-DLStruct==0.1) (1.7.1) 
> Requirement already satisfied: numpy~=1.16.4 in c:\users\ymu\appdata\local\ucsf\chimerax\1.1\site-packages (from ChimeraX-DLStruct==0.1) (1.16.6) 
> Requirement already satisfied: typing-extensions in c:\users\ymu\appdata\local\ucsf\chimerax\1.1\site-packages (from torch~=1.7.1->ChimeraX-DLStruct==0.1) (3.7.4.3) 
> Collecting quadprog~=0.1.7 
> Using cached quadprog-0.1.8.tar.gz (269 kB) 
> Requirement already satisfied: Cython in c:\program files\chimerax 1.1\bin\lib\site-packages (from quadprog~=0.1.7->ChimeraX-DLStruct==0.1) (0.29.20) 
> Collecting importlib-metadata~=0.17 
> Using cached importlib_metadata-0.23-py2.py3-none-any.whl (28 kB) 
> Requirement already satisfied: zipp>=0.5 in c:\users\ymu\appdata\local\ucsf\chimerax\1.1\site-packages (from importlib-metadata~=0.17->ChimeraX-DLStruct==0.1) (3.4.1) 
> Building wheels for collected packages: quadprog 
> Building wheel for quadprog (setup.py): started 
> Building wheel for quadprog (setup.py): finished with status 'error' 
> Running setup.py clean for quadprog 
> Failed to build quadprog 
> Installing collected packages: quadprog, importlib-metadata, ChimeraX-DLStruct 
> Running setup.py install for quadprog: started 
> Running setup.py install for quadprog: finished with status 'error' 
> ERROR: Command errored out with exit status 1: 
> command: 'C:\Program Files\ChimeraX 1.1\bin\ChimeraX.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ymu\\AppData\\Local\\Temp\\pip-install-xakoctiw\\quadprog_7cb25d8bb3904ea3b64643e58389ec80\\setup.py'"'"'; __file__='"'"'C:\\Users\\ymu\\AppData\\Local\\Temp\\pip-install-xakoctiw\\quadprog_7cb25d8bb3904ea3b64643e58389ec80\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ymu\AppData\Local\Temp\pip-wheel-gloxcthl' 
> cwd: C:\Users\ymu\AppData\Local\Temp\pip-install-xakoctiw\quadprog_7cb25d8bb3904ea3b64643e58389ec80\ 
> Complete output (6 lines): 
> running bdist_wheel 
> running build 
> running build_ext 
> skipping 'quadprog\quadprog.cpp' Cython extension (up-to-date) 
> building 'quadprog' extension 
> error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/ 

---------------------------------------- 

> ERROR: Command errored out with exit status 1: 'C:\Program Files\ChimeraX 1.1\bin\ChimeraX.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ymu\\AppData\\Local\\Temp\\pip-install-xakoctiw\\quadprog_7cb25d8bb3904ea3b64643e58389ec80\\setup.py'"'"'; __file__='"'"'C:\\Users\\ymu\\AppData\\Local\\Temp\\pip-install-xakoctiw\\quadprog_7cb25d8bb3904ea3b64643e58389ec80\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ymu\AppData\Local\Temp\pip-record-gcrsp7lk\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\ymu\AppData\Local\UCSF\ChimeraX\Python37\Include\quadprog' Check the logs for full command output. 
> WARNING: You are using pip version 20.2.2; however, version 21.0.1 is available. 
> You should consider upgrading via the 'C:\Program Files\ChimeraX 1.1\bin\ChimeraX.exe -m pip install --upgrade pip' command.

**Comment by stephane-caron** [comment]
From your error log:

> error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

Have you installed these Visual C++ Build Tools? You will need them to use `qpsolvers`.

**Comment by Yongcheng123** [comment]
> From your error log:
> 
> > error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
> 
> Have you installed these Visual C++ Build Tools? You will need them to use `qpsolvers`.

Yes, thank you for your help. I already fix that issue by installing a Visual C++ Build Tools.
