### ISSUE TITLE
lb and ub make matrix G dense

### ISSUE THREAD

**Issue by MeindertHH** [stephane-caron/qpsolvers#44]
Hi Stephane! I very much enjoy your package.

I found that lb and ub only work with dense matrices. For these inequality constraints, the concatenate function of NumPy is used. This returns a np.ndarray, which in my case is way too large to fit into memory.

Would you consider adding 'vstack' from the SciPy.sparse library instead to solve this problem? E.g. in file `__init__.py`:

```Python
    if lb is not None:
        if G is None:
            G = -eye(len(q))
            h = -lb
        else:  # G is not None and h is not None
            if type(G) is ndarray:
                G = concatenate((G, -eye(len(q))), 0)
            else:
                from scipy import sparse
                G = sparse.vstack([G, -sparse.eye(len(q))])
            h = concatenate((h, -lb))
    if ub is not None:
        if G is None:
            G = eye(len(q))
            h = ub
        else:  # G is not None and h is not None
            if type(G) is ndarray:
                G = concatenate((G, eye(len(q))), 0)
            else:
                from scipy import sparse
                G = sparse.vstack([G, -sparse.eye(len(q))])
            h = concatenate((h, ub))
```

Thank you in advance for your consideration!

If you'd prefer, I can make a pr. I did not consider cvxopt.spmatrix.

**Comment by stephane-caron** [comment]
Thanks for your proposal and the working code :+1: This case was indeed missing. I just pushed it to `master` for the upcoming 1.7.0 release, feel free to try it out and let us know if it works for you.

Do you have some small examples we could add as unit tests?

**Comment by stephane-caron** [comment]
Added unit tests in the fresh release of v1.7. They helped catch [this bug](https://github.com/stephane-caron/qpsolvers/commit/69d662da9e52c829a8106f2024bebc1cba85246e) when stacking both lower and upper bounds.
