### ISSUE TITLE
cvxopt was moved to an optional dependency but is still required

### ISSUE THREAD

**Issue by adamoppenheimer** [stephane-caron/qpsolvers#46]
The title says it all. This issue seems to have arisen with the newest version of qpsolvers. I'm running this on MacOS 10.15.7, with Python 3.9.7 and qpsolvers 1.7.0 - let me know if you'd like any more information.

I would also like to point out this issue is relevant to me because I help maintain the package [pytwoway](https://github.com/tlamadon/pytwoway) which uses qpsolvers as a dependency (and I have to send lots of thanks for the package! It is excellent). I will need to update pytwoway's dependencies to either use an older version of qpsolvers or to additionally include cvxopt if it will no longer be included by default in qpsolvers.

This is the output when I try to run
```python
from qpsolvers import solve_qp
```

without `cvxopt` installed (it's the same output for `solve_ls` instead of `solve_qp`):

```python
In [1]: from qpsolvers import solve_qp
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-b46fa005102a> in <module>
----> 1 from qpsolvers import solve_qp

~/opt/anaconda3/envs/temp-env2/lib/python3.9/site-packages/qpsolvers/__init__.py in <module>
     21 """Quadratic programming solvers in Python with a unified API"""
     22
---> 23 from .solve_ls import solve_ls
     24 from .solve_qp import solve_qp
     25 from .solve_qp import solve_safer_qp

~/opt/anaconda3/envs/temp-env2/lib/python3.9/site-packages/qpsolvers/solve_ls.py in <module>
     27 from numpy import dot, ndarray
     28
---> 29 from .solve_qp import solve_qp
     30 from .typing import Matrix, Vector
     31

~/opt/anaconda3/envs/temp-env2/lib/python3.9/site-packages/qpsolvers/solve_qp.py in <module>
     28
     29 from .check_problem_constraints import check_problem_constraints
---> 30 from .concatenate_bounds import concatenate_bounds
     31 from .exceptions import SolverNotFound
     32 from .solvers import dense_solvers

~/opt/anaconda3/envs/temp-env2/lib/python3.9/site-packages/qpsolvers/concatenate_bounds.py in <module>
     23 from typing import Optional, Tuple
     24
---> 25 import cvxopt
     26 import numpy as np
     27

ModuleNotFoundError: No module named 'cvxopt'
```

**Comment by stephane-caron** [comment]
Thank you for reporting this! It was my oversight when I added type annotations in 1.7.0, CVXOPT types should be handled separately. This is now taken care of in 1.7.1 which is [just released](https://github.com/stephane-caron/qpsolvers/releases/tag/v1.7.1).

I'm happy to know qpsolvers can be of some help :smiley: It should work as before now and you shouldn't have anything to change in PyTwoWay. Otherwise let me know.
