### ISSUE TITLE
Issue with a quadprog (version 0.1.10)

### ISSUE THREAD

**Issue by junhyeokahn** [stephane-caron/qpsolvers#47]
Hello,
Thanks for maintaining this nice repo!

I just find one example that the ```quadprog``` solver is stuck in the infinite loop.
Here, I am attaching the zip file for the example problem.

The latest qpsolvers installation (```pip3 install qpsolvers```) installs the ```quadprog``` (version 0.1.10).
With this, when I run ```python3 main.py```, it goes into infinite loop.
However, if I run it with ```cvxopt``` (version 1.2.7) after installing it by (```pip3 install cvxopt```), it gives a solution.
I also found that the older version of ```quadprog``` (version 0.1.8) is able to solve the same problem, and the solution is very close to the solution achieved from cvxopt.

It looks like an issue regarding the ```quadprog``` package, and my apologies if I am leaving an issue in the wrong place.

[qp.zip](https://github.com/stephane-caron/qpsolvers/files/7508138/qp.zip)

**Comment by stephane-caron** [comment]
Confirmed! Thanks for this accurate issue report.

This looks like a quadprog issue indeed, let's continue the discussion at https://github.com/quadprog/quadprog/issues/32. In the meantime, I recommend using quadprog 0.1.8 or 0.1.9 for which this problem doesn't show up.

**Comment by junhyeokahn** [comment]
Thanks for taking care of this!

**Comment by stephane-caron** [comment]
Fixed upstream. I checked your example with quadprog 0.1.11 and now it runs just fine :ok_hand:
