### ISSUE TITLE
kwargs don't get passed to OSQP

### ISSUE THREAD

**Issue by urob** [stephane-caron/qpsolvers#59]
During the setup of the OSQP solver in `osqp_.py` user-supplied `kwargs` are overwritten by:

```
kwargs = {
        "eps_abs": eps_abs,
        "eps_rel": eps_rel,
        "polish": polish,
        "verbose": verbose,
    }
```

It would be preferably to update the user-supplied arguments using `kwargs.update({...})`

**Comment by stephane-caron** [comment]
Thank you for the report! This is fixed now.
