### ISSUE TITLE
Waiting for warm-start to hit highspy wrapper

### ISSUE THREAD

**Issue by stephane-caron** [stephane-caron/qpsolvers#94]
It seems warm-start is possible https://github.com/ERGO-Code/HiGHS/issues/617

**Comment by stephane-caron** [comment]
It seems the ``get/setHotStart`` functions are not wrapped by [highspy](https://pypi.org/project/highspy/) yet.

**Comment by jajhall** [comment]
We won't be wrapping the `get/setHotStart` functions as these are specialised methods for the MIP solver. As discussed in https://github.com/ERGO-Code/HiGHS/issues/617#issuecomment-982148533 HiGHS will hot start as much as possible automatically, depending on the modifications made to the incumbent model.

**Comment by stephane-caron** [comment]
I see, thanks for explaining this! Then for warm-starting users would need a mechanism to recover the internal ``highspy.Highs`` instance, which is not possible with the current qpsolvers API.

The challenge for qpsolvers is to provide an API that works across solvers. For warm-starting, currently it's only a primal vector (for the next revision it will likely be primal and dual vectors).

**Comment by stephane-caron** [comment]
For the next (API-changing) revision we can think of a mechanism to pass around solvers' internal states, but I'm not sure how much demand there would be for that. Everyone is welcome to :+1: this message if demand there is :wink:

**Comment by jajhall** [comment]
> I see, thanks for explaining this! Then for warm-starting users would need a mechanism to recover the internal `highspy.Highs` instance, which is not possible with the current qpsolvers API.

So, once you've solved the incumbent model in the `highspy.Highs` instance, then this instance is destroyed? In this case you need the model and optimal HighsBasis in order to hot start...

... but if the model is modified by the user, then it may not be possible to use the optimal HighsBasis.

If you've still got the `highspy.Highs` instance then nothing has to be done

Maybe we need to discuss this properly

**Comment by stephane-caron** [comment]
> So, once you've solved the incumbent model in the highspy.Highs instance, then this instance is destroyed?

Yes, that's the current implementation.

In qpsolvers the user calls ``solve_qp(P, q, G, h, A, b, lb, ub, initvals=x_0)``, where ``P, q, G, h, A, b, lb, ub`` are the matrices defining the model, and ``initvals`` is the warm-start primal guess. The return value is either ``None`` (unfeasible) or the primal solution vector. Then, if the model changes, the user updates ``P, q, G, h, A, b, lb, ub``, and can provide the solution to the previous model as initial guess. (That's a common pattern for *e.g.* model predictive control.)

> If you've still got the highspy.Highs instance then nothing has to be done

Yes, the ``highspy.Highs`` instance would be what I called the solver's "internal state" above.

But then, assuming we still have [that instance](https://github.com/stephane-caron/qpsolvers/blob/bc8310be7fa6be76e72bc1ce2b7f36d8775c1565/qpsolvers/solvers/highs_.py#L239) at the next warm-started function call, it would still be passed a new model (built from the new matrices ``P, q, G, h, A, b, lb, ub``):

```python
    solver = highspy.Highs()  # let's assume we have it at next warm-started call
    solver.passModel(model)
```

I think that's what you mean by "the model is modified by the user".
